package os.elastos.hey.social

// AUTO-GENERATED from mobile/hey-verse/catalog_glb/manifest.json (VerseCatalog.all()).
// The native Verse Library + Edit-avatar sheets list these; tapping posts a
// ui command ("place:<id>" / "wear:<id>") that home.gd's editor executes.
data class VerseItem(val id: String, val name: String, val kind: String, val rarity: String, val desc: String)

object VerseCatalogData {
    val items: List<VerseItem> = listOf(
        VerseItem("party_hat", "Confetti Cone Deluxe", "hat", "Common", "A candy-striped lacquer party cone topped with a glowing star and a burst of floating confetti that never lands."),
        VerseItem("top_hat", "Midnight Dapper Topper", "hat", "Uncommon", "A tall midnight-felt top hat with crimson satin, a brass buckle, a pearl stick-pin, and a tucked silk rose for the disce"),
        VerseItem("propeller_cap", "Whirlybird Beanie", "hat", "Uncommon", "A stitched four-colour gore-panel beanie crowned with a real chrome-post propeller caught mid-spin."),
        VerseItem("cat_ears", "Kawaii Bell Ears", "hat", "Uncommon", "A glossy headband with plush two-tone cat ears, dainty whiskers, a pink crest sparkle, and gold bell charms that beg to "),
        VerseItem("viking_helmet", "Forged Frosthorn Helm", "hat", "Rare", "A brushed-iron war helm with a riveted brass brow band, a forged nose guard, a ruby finial, and a pair of banded bone ho"),
        VerseItem("headphones", "Studio Glow Cans", "hat", "Rare", "Audiophile studio headphones with a chrome slider band, plush memory-foam cups ringed in glowing cyan, a boom mic, and l"),
        VerseItem("flower_crown", "Wildbloom Coronet", "hat", "Rare", "A woven vine crown bursting with layered multi-petal blossoms, glowing pollen hearts, ruby berries, and trailing ivy."),
        VerseItem("wizard_hat", "Starweaver's Cap", "hat", "Epic", "A tall droopy indigo wizard hat dusted with emissive stars and a crescent moon, ringed by a gold band of bezel-set gems,"),
        VerseItem("crown", "Sovereign's Jewel Crown", "hat", "Epic", "A regal polished-gold crown of five fleur points crowned with faceted ruby, sapphire, and emerald jewels, bezel-set frie"),
        VerseItem("halo", "Seraph's Winged Halo", "hat", "Epic", "A floating forged-gold halo of scrollwork and bezel-set sapphires, flanked by a pair of layered celestial feather wings "),
        VerseItem("astronaut_helmet", "Orbit Pioneer Helm", "hat", "Legendary", "A glossy spacesuit helmet with a clear tinted glass dome over a glowing cyan visor, a gold sun-shield, head lamps, hose "),
        VerseItem("flame_crown", "Emberlord's Blaze Crown", "hat", "Legendary", "A blackened-gold crown with molten ember seams, wreathed in living flame tongues that burn red to white-hot, a glowing g"),
        VerseItem("velvet_armchair", "Periwinkle Plush Armchair", "seating", "Uncommon", "A button-tufted periwinkle velvet armchair with brass nailhead trim, curling wing arms and gold-piped cushions on turned"),
        VerseItem("royal_throne", "Crown Sovereign Throne", "seating", "Legendary", "A towering crimson-velvet throne on a stepped gold dais, crowned with a spiked gold crest, faceted glowing gemstones, li"),
        VerseItem("gaming_chair", "Neon Apex Racer", "seating", "Rare", "A glossy carbon racing bucket seat with cyan-and-magenta neon trim, a glowing winged emblem, headrest and lumbar pillows"),
        VerseItem("beanbag", "Sunset Slouch Beanbag", "seating", "Common", "A slouchy two-tone mustard-and-pumpkin beanbag with stitched gore seams, a drawcord top knot, a little leather brand pat"),
        VerseItem("carved_dining_chair", "Heritage Walnut Chair", "seating", "Uncommon", "A heritage walnut dining chair with a turned spindle back, a ribbon-carved splat, a gilt crest medallion, fluted legs wi"),
        VerseItem("mushroom_stool", "Toadstool Fairy Seat", "seating", "Rare", "A whimsical candy-red toadstool stool with cream spots, softly glowing gills underneath, a chubby cream stalk, a tiny la"),
        VerseItem("swing_seat", "Honey Rattan Egg Swing", "seating", "Epic", "A hanging honey-rattan egg chair on a gunmetal gooseneck stand, with a deep seafoam cushion, a tasselled coral pillow, t"),
        VerseItem("chesterfield_sofa", "Oxblood Chesterfield", "seating", "Epic", "A deep button-tufted oxblood-leather Chesterfield with low rolled arms, double rows of brass studs, a folded cream throw"),
        VerseItem("hammock", "Seaside Stripe Hammock", "seating", "Rare", "A striped teal-and-coral canvas hammock slung between two A-frame wooden posts, with rope fans, a fringed edge, a sunny "),
        VerseItem("cloud_sofa", "Dreamcloud Sofa", "seating", "Legendary", "An oversized sofa sculpted from puffy pastel cloud lobes with a sky-blue gradient underside, a soft glow rim, a rising r"),
        VerseItem("marble_coffee_table", "Veined Marble Lounge Table", "table", "Rare", "A beveled veined-marble slab floats on a brass cross-frame, crowned with a turned candlestick, a fruit dish, and a singl"),
        VerseItem("oak_dining_table", "Honest Oak Farmhouse Table", "table", "Uncommon", "A big planked-oak farmhouse table with iron-strapped chamfered legs, a linen runner, a ceramic fruit bowl, and a warm ca"),
        VerseItem("glowing_desk", "Neon Battlestation Desk", "table", "Epic", "A graphite cyber-desk with RGB edge grooves, a glowing monitor, a fan-lit tower, a headphone stand, and a tiny glowing d"),
        VerseItem("ornate_bookshelf", "Grand Mahogany Library Case", "table", "Legendary", "A carved mahogany library case with fluted gold columns, a gem-crowned arched pediment, a golden mantel clock, busts, an"),
        VerseItem("treasure_chest", "Overflowing Pirate Hoard", "table", "Epic", "A studded oak chest cracked open on gold hinges, spilling glowing coins, a crown jewel, scattered gems, and a rolled tre"),
        VerseItem("apothecary_cabinet", "Herbalist's Apothecary Chest", "table", "Rare", "A sage-teal chest of labelled brass-handled drawers under a glass display of glowing potions, with a stone mortar and a "),
        VerseItem("crystal_side_table", "Amethyst Geode Pedestal", "table", "Legendary", "A faceted amethyst slab on a glowing geode cluster rising from a gold base ring, topped by a hero crown gem and orbiting"),
        VerseItem("arcade_cabinet", "Neon Dreams Arcade Cabinet", "table", "Epic", "A retro upright arcade machine with a glowing marquee emblem, a lit game screen, a joystick and candy-colored buttons, a"),
        VerseItem("terrarium_table", "Living Biome Terrarium Table", "table", "Rare", "A glass-tank coffee table holding a tiny world of mossy mounds, a little tree, a glowing pond, luminous mushrooms, and d"),
        VerseItem("floating_shelf", "Floating Live-Edge Display Shelf", "table", "Uncommon", "A thick live-edge plank on hidden metal brackets with a brass lip and warm underglow, styled with a lit picture, books, "),
        VerseItem("art_deco_lamp", "Gatsby Torchiere", "lighting", "Rare", "A glamorous Art-Deco floor lamp where a black-marble ziggurat, fluted brass column and golden sunburst fan cradle a glow"),
        VerseItem("lantern_string", "Festival Lantern Garland", "lighting", "Uncommon", "Five pleated rice-paper lanterns in candy festival colors swing from a catenary cord with fluttering bunting, gold crown"),
        VerseItem("chandelier", "Crown of a Thousand Tears", "lighting", "Legendary", "A multi-tier gold chandelier cascading with faceted crystal drops, six live candle-flames, ruby-set arms and a rising sh"),
        VerseItem("neon_sign", "HEY Neon", "lighting", "Epic", "A buzzing cursive 'HEY' in hot-magenta neon tubing with a cyan swoosh, an amber star and a haloed glow off a brushed bac"),
        VerseItem("lava_lamp", "Groovy Goo Lamp", "lighting", "Uncommon", "A retro lava lamp on a reeded chrome cone with peg feet and a glowing power knob, blobbing hot orange and magenta wax up"),
        VerseItem("campfire", "Cozy Campfire", "lighting", "Common", "A ring of mossy river stones around crossed birch logs and a layered leaping flame that throws up a cheerful spray of da"),
        VerseItem("fairy_jar", "Jar of Caught Stars", "lighting", "Rare", "A corked mason jar tied with twine and a tiny brass keepsake tag, brimming with a slow swirl of golden fireflies twinkli"),
        VerseItem("street_lamp", "Old Town Gaslamp", "lighting", "Common", "A storybook cast-iron gaslamp with a fluted post, C-scroll brackets, a six-sided glass lantern, a vented copper crown an"),
        VerseItem("mushroom_lamp", "Glowcap Grove", "lighting", "Epic", "A mossy mound sprouting three bioluminescent toadstools with spotted caps and frilled glowing gills, a curled fern, glow"),
        VerseItem("ornate_painting", "Golden Hour Masterpiece", "wallart", "Epic", "A museum-grade gilt frame cradling a glowing sunset-over-the-lake oil scene, lit by its own brass picture light."),
        VerseItem("neon", "HEY! Neon Sign", "wallart", "Rare", "A buzzing glass-tube HEY wordmark with a pink heart and one cheekily flickering dead segment, washing the wall in candy "),
        VerseItem("gilded_mirror", "Sunburst Oracle Mirror", "wallart", "Legendary", "A double-ring sunburst of pointed gold rays surrounds a faceted mirror crowned with a giant ruby and a halo of glowing g"),
        VerseItem("grand_clock", "Gilded Heirloom Clock", "wallart", "Epic", "A stately beaded-bezel clock frozen at a friendly 10:10, with ornate hands, a gem center cap and a glowing swinging pend"),
        VerseItem("pixel_screen", "8-Bit Sunrise CRT", "wallart", "Uncommon", "A chunky beige CRT glowing with a pixel-art sunrise and a tiny hero sprite, complete with scanlines, vent slats and twid"),
        VerseItem("pennant", "Champions Felt Pennant", "wallart", "Common", "A two-tone felt championship pennant on a turned wood dowel, sporting an appliqué star roundel, a stitched #1 and bobble"),
        VerseItem("butterfly_display", "Jeweled Lepidoptera Case", "wallart", "Rare", "A deep shadow-box of six jewel-bright butterflies pinned on linen behind glass, each with a chrome pin and tiny museum l"),
        VerseItem("vinyl_wall", "Now Playing Vinyl", "wallart", "Uncommon", "A glossy grooved LP spinning over sunburst sleeve art, finished with a yellow 45 adapter and a gold now-playing plaque."),
        VerseItem("holo_poster", "Holo Planetarium Panel", "wallart", "Legendary", "A frameless acrylic sheet projecting a glowing wireframe planet, tilted orbit rings, gem nodes and drifting data motes f"),
        VerseItem("monstera", "Splitleaf Sweetheart", "plant", "Common", "A friendly split-leaf monstera fanning eight glossy paddles from a teal-banded deco pot."),
        VerseItem("bonsai", "Whispering Elder Bonsai", "plant", "Uncommon", "A tiny ancient tree trained with spiralling copper wire on an oxblood-glaze tray, its cloud pads dusted with pink blosso"),
        VerseItem("cherry_blossom", "Sakura Lantern Tree", "plant", "Rare", "A blushing sakura strung with warm fairy-lights on a brass-banded stone planter, raining soft petals."),
        VerseItem("crystal_plant", "Aurora Geode Bloom", "plant", "Epic", "Bioluminescent gem shards rise from a gold-pronged obsidian geode beneath a hovering keystone jewel and a halo of sparks"),
        VerseItem("cactus_trio", "Desert Buddy Trio", "plant", "Common", "A saguaro, a ribbed barrel and a prickly pear share one zigzag-painted pot, each crowned with a cheerful bloom."),
        VerseItem("topiary_cat", "Hedge Cat of the Garden", "plant", "Rare", "A sculpted hedge shaped into a sitting cat with glowing eyes, wearing a real gold collar, amber bell and a gemstone char"),
        VerseItem("hanging_fern", "Boho Cascade Fern", "plant", "Uncommon", "A lush trailing fern spilling from a beaded macramé hanger on a polished brass ring, dotted with coral spore-bells."),
        VerseItem("sunflower_patch", "Sunny Day Crate", "plant", "Common", "A trio of beaming sunflowers with double petal rings nod over a slatted wooden crate while a little bee hovers by."),
        VerseItem("potted_palm", "Tradewind Brass Palm", "plant", "Uncommon", "A breezy fan palm arches from a brass-banded woven basket, hiding a pair of coconuts beneath its crown."),
        VerseItem("carnivorous", "Nectar Trap Bog", "plant", "Epic", "Toothy flytraps and a glowing pitcher rise from a gold-rimmed mossy bog, each lure beaded with a faceted amber dewdrop a"),
        VerseItem("zen_garden", "Imperial Zen Sanctuary", "plant", "Legendary", "A gold-inlaid raked-sand tray with balancing stones, a maple sprig, a gem-set gilded lantern, a glowing koi chip and a h"),
        VerseItem("rug", "Madder Medallion Rug", "decor", "Common", "A plush hand-knotted wool rug whose radiating star medallion makes any spot on the floor feel like home."),
        VerseItem("vase", "Porcelain Posy Vase", "decor", "Uncommon", "A glossy teal-glaze vase with gold filigree handles, brimming with a freshly-cut spring posy."),
        VerseItem("statue", "Golden Hero Monument", "decor", "Epic", "A proud civic statue of your robot kind cast in solid gold, gem-set and glowing, atop a laureled marble plinth."),
        VerseItem("fountain", "Grand Cascade Fountain", "decor", "Legendary", "A three-tier stone fountain crowned with a ruby finial, ringed by golden dolphin spouts and lily pads, pouring lit, spar"),
        VerseItem("snowglobe", "Winter Village Globe", "decor", "Rare", "A whole snowy hamlet under glass: a lit cottage, a pine, a top-hatted snowman and a glowing lamppost, dusted by drifting"),
        VerseItem("gramophone", "Brass Morning-Glory Gramophone", "decor", "Rare", "A vintage phonograph with a great fluted brass horn and a spinning record, trailing glowing music notes into the air."),
        VerseItem("telescope", "Observatory Refractor", "decor", "Epic", "A polished brass refractor on a wooden tripod, star-map ring set, aimed at a tiny glowing constellation only it can see."),
        VerseItem("aquarium", "Living Reef Aquarium", "decor", "Epic", "A lit reef tank alive with neon fish, branching coral, a tiny castle and a curtain of rising bubbles, all on a wood cabi"),
        VerseItem("crystal", "Hovering Arcane Crystal", "decor", "Legendary", "A faceted arcane gem that hovers above a runed pedestal, ringed by orbiting shards and floating glyphs in a beam of ener"),
        VerseItem("balloons", "Party Balloon Bunch", "decor", "Uncommon", "Five glossy jewel-tone helium balloons led by a gold foil star, curled ribbons tied to a wrapped gift, with drifting con"),
        VerseItem("trophy", "Champions' Cup", "decor", "Rare", "A gleaming gold cup with looping handles and a laurel wreath, set with emeralds on an obsidian base, crowned by a bursti"),
    )
    val hats: List<VerseItem> get() = items.filter { it.kind == "hat" }
    val objects: List<VerseItem> get() = items.filter { it.kind != "hat" }
    val objectKinds: List<Pair<String,String>> = listOf(
        "" to "All", "seating" to "Seating", "table" to "Tables", "lighting" to "Lighting",
        "wallart" to "Wall art", "plant" to "Plants", "decor" to "Decor")
}
